### ISSUE TITLE
Question: How can I get the Albums of the current user?

### ISSUE THREAD

**Issue by Nerian** [moomerman/facebook_oauth#5]
I want to download all the photos of the loged user. How can I do that?

**Comment by moomerman** [comment]
Once you have the user logged in you can access all the albums with:

client.me.albums

then for each album id you can call:

client.me.albums('album_id').photos

to access each photo.

**Comment by moomerman** [comment]
Also, you'll need to make sure you have the 'user_photos' permission.  See the readme for an example.

**Comment by Nerian** [comment]
I configured my app so that it ask for the right permissions.

client.me.albums returns a bunch of data. How do I access that data? Do I have to parse it?

What I want to achieve is something like:

```
client.me.albums do | album |
    client.me.album(album).photos do | photo |
        source = client.me.photo(photo).source
        ...get the actual photo and save it to disk...      
        end
    end
end
```

Just get all the photos images. How do I do that?

Thanks!

**Comment by moomerman** [comment]
The data needs a little processing, I think this should work:

```
client.me.albums['data'].each do |album|
    client.me.albums(album['id']).photos['data'].each do |photo|
        source = client.me.photos(photo['id']).source # not sure if you need to do source['data']
    end
end
```

**Comment by Nerian** [comment]
I tried with this code:

```
 client.me.albums['data'].each do |album|
    client.me.albums(album['id']).photos['data'].each do |photo|
        source = client.me.photos(photo['id']).source # not sure if you need to do source['data']
        file = open(source)
        content = file.read()
        File.open("#{RAILS_ROOT}/tmp/export/album/#{photo['id']}.jpg", 'w') {|f| content }
    end
end
```

But I get this error:

```
 NoMethodError (undefined method `photos' for #<Hash:0x2b733d157760>):
   app/controllers/application_controller.rb:28:in `generate_album_file'
   app/controllers/application_controller.rb:27:in `each'
   app/controllers/application_controller.rb:27:in `generate_album_file'
   app/controllers/export_controller.rb:10:in `create'
```

**Comment by Nerian** [comment]
More input:

```
client.me.albums['data'].each do |album|   
```

It returns:

An album object has:

```
{
  "name": "Profile Pictures",
  "cover_photo": "149363641741115",
  "from": {
    "name": "Gonzalo Rodriguez-Baltanas",
    "id": "100000024399383"
  },
  "id": "155596787784467",
  "created_time": "2010-08-24T00:13:01+0000",
  "type": "profile",
  "count": 3,
  "updated_time": "2010-07-31T15:44:42+0000",
  "privacy": "friends-of-friends",
  "link": "http://www.facebook.com/album.php?aid=32886&id=100000024399383"
}
```

This:

```
client.me.albums(album['id'])
```

Returns:

```
{
  "data": [
    {
      "name": "Profile Pictures",
      "cover_photo": "149363641741115",
      "from": {
        "name": "Gonzalo Rodriguez-Baltanas",
        "id": "100000024399383"
      },
      "id": "155596787784467",
      "created_time": "2010-08-24T00:13:01+0000",
      "type": "profile",
      "count": 3,
      "updated_time": "2010-07-31T15:44:42+0000",
      "privacy": "friends-of-friends",
      "link": "http://www.facebook.com/album.php?aid=32886&id=100000024399383"
    },
    {
      "name": "Perfil",
      "cover_photo": "100358483308298",
      "from": {
        "name": "Gonzalo Rodriguez-Baltanas",
        "id": "100000024399383"
      },
      "id": "100358313308315",
      "created_time": "2009-05-23T09:41:17+0000",
      "type": "normal",
      "count": 4,
      "updated_time": "2011-03-14T20:54:50+0000",
      "privacy": "friends-of-friends",
      "link": "http://www.facebook.com/album.php?aid=618&id=100000024399383"
    }
  ],
  "paging": {
    "previous": "https://graph.facebook.com/me/albums?access_token=104108729662859%7C83fe67becfe282e63eeb5f09-100000024399383%7CpmNjqElc9fE52SMWwBNo2HGrMTA&limit=25&since=1282608781",
    "next": "https://graph.facebook.com/me/albums?access_token=104108729662859%7C83fe67becfe282e63eeb5f09-100000024399383%7CpmNjqElc9fE52SMWwBNo2HGrMTA&limit=25&until=1243071677"
  }
}
```

Notice that it is NOT just the album object it should have returned. It the the whole array of albums. It should just return the specified album, isn't it?

This line:

```
client.me.albums(album['id']).each do |photo|
```

A photo object has:

```
[
  "data",
  [
    {
      "name": "Profile Pictures",
      "cover_photo": "149363641741115",
      "from": {
        "name": "Gonzalo Rodriguez-Baltanas",
        "id": "100000024399383"
      },
      "id": "155596787784467",
      "created_time": "2010-08-24T00:13:01+0000",
      "type": "profile",
      "count": 3,
      "updated_time": "2010-07-31T15:44:42+0000",
      "privacy": "friends-of-friends",
      "link": "http://www.facebook.com/album.php?aid=32886&id=100000024399383"
    },
    {
      "name": "Perfil",
      "cover_photo": "100358483308298",
      "from": {
        "name": "Gonzalo Rodriguez-Baltanas",
        "id": "100000024399383"
      },
      "id": "100358313308315",
      "created_time": "2009-05-23T09:41:17+0000",
      "type": "normal",
      "count": 4,
      "updated_time": "2011-03-14T20:54:50+0000",
      "privacy": "friends-of-friends",
      "link": "http://www.facebook.com/album.php?aid=618&id=100000024399383"
    }
  ]
]
```

Which is one album, not one photo. That's normal, as  `client.me.albums(album['id'])`is returning the whole array of albums.

**Comment by Nerian** [comment]
Any idea?
